# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel

warnings_are_errors: true
sudo: false
cache: packages

repos:
  CRAN: https://cloud.r-project.org

notifications:
  email:
    on_success: true
    on_failure: true
