# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel

warnings_are_errors: true
sudo: false
cache: packages

install:
  - ./travis-tool.sh install_r MASS
  - ./travis-tool.sh install_r lmtest
  - ./travis-tool.sh install_r sandwich

repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - MASS
  - lmtest
  - sandwich

env:
  global:
      - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: true
    on_failure: true
