# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r:
  - oldrel
  - release
  - devel

warnings_are_errors: true
sudo: false
cache: packages

r_packages:
  - covr

after_success:
  - Rscript --verbose -e 'library(covr); print("output to console"); codecov()'

repos:
  CRAN: https://cloud.r-project.org

notifications:
  email:
    recipients:
      - siegfried.koestlmeier@gmail.com
    on_success: always
    on_failure: always
