# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel

warnings_are_errors: true
sudo: false
cache: packages

r_github_packages:
  - cran/MASS
  - cran/lmtest
  - cran/sandwich

env:
  global:
      - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: true
    on_failure: true
